### ISSUE TITLE
Add some Debian patches

### ISSUE THREAD

**Issue by mirandir** [MCMic/jumpnbump#1]
Hello,

Thanks for this SDL2 port of Jump'n'Bump!

Folks of Debian have some interesting patches you could import in your code.
Especially:
- format-security.patch
- safe-temporary-files.patch
- no-springs.patch (this one is important for players, because it fixes an annoying bug which make rabbits can disappear when jumping out of the screen. I have tested, your SDL2 port still has this bug).

You can find this patches in the Debian archive or in my AUR package : https://aur.archlinux.org/packages/jumpnbump/

**Comment by MCMic** [comment]
Thanks, I will look into it!

**Comment by MCMic** [comment]
format-security and no-springs are simple and quite short, I will include them. Can you explain how to reproduce the disappearing bug through?
As for safe-temporary-files, I can apply it as is because it won’t work for windows users. (And I’m not sure what it’s for)

Your Makefile patch is weird too, it sets PREFIX to /usr by default and then uses $PREFIX/usr as a folder, that would put things in /usr/usr by default…
You should use make PREFIX=/usr instead of most of this patch. (the only thing you do need to patch is put the binary in bin and not games. I might change that here too, games is not standard afaik)

**Comment by mirandir** [comment]
You're right, it seems I have messed up my Makefile patch. Updated.

For the bug, you have details on the Debian bugreport : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=370650. I attach a little video which shows the bug :[jnb_bug.webm.zip](https://github.com/MCMic/jumpnbump/files/61202/jnb_bug.webm.zip)

Another important patch according to Debian is NetPacket_buffer_size.patch : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762698. I don't know if it's really still needed.

**Comment by MCMic** [comment]
Everything appart from safe-temporary-files.patch is pushed.
Makefile is now putting the binary in bin instead of games, but default prefix is still /usr/local as it should be, just use "make PREFIX=/usr" when packaging.

**Comment by mirandir** [comment]
Perfect. Thank you !
